import { Portfolio } from '../data/mockData';

export const fakeAuthUser = {
    id: 'user-1',
    email: 'neh5284@psu.edu',
};

export const fetchedBasicUser = {
    id: 'user-1',
    name: 'Nathan Hinkle',
    email: 'neh5284@psu.edu',
    created_at: '2026-01-01T00:00:00.000Z',
};

export const fetchedBasicPortfolio = {
    id: 'portfolio-1',
    user_id: 'user-1',
    title: 'Nathan Portfolio',
    username: 'neh5284',
    bio: 'Human-Centered Design and Development student.',
    tagline: 'Building the future, one project at a time.',
    visibility: 'public' as const,
    created_at: '2026-01-01T00:00:00.000Z',
};

export const fetchedBasicProjects = [
    {
        id: 'project-1',
        portfolio_id: 'portfolio-1',
        title: 'Alpha Project',
        description: 'React dashboard project',
        source_type: 'github',
        source_url: 'https://github.com/neh5284/alpha',
        status: 'verified',
        created_at: '2026-01-02T00:00:00.000Z',
        category: 'coding',
        tags: ['React', 'Supabase'],
        github_url: 'https://github.com/neh5284/alpha',
        project_url: 'https://example.com/alpha',
        image_url: null,
        is_group_project: true,
        personal_contribution: 'Owned the frontend dashboard.',
        is_public: true,
    },
    {
        id: 'project-2',
        portfolio_id: 'portfolio-1',
        title: 'Beta Design',
        description: 'Visual identity project',
        source_type: 'manual',
        source_url: null,
        status: 'published',
        created_at: '2026-03-05T00:00:00.000Z',
        category: 'design',
        tags: ['Figma'],
        github_url: null,
        project_url: null,
        image_url: null,
        is_group_project: false,
        personal_contribution: null,
        is_public: true,
    },
    {
        id: 'project-3',
        portfolio_id: 'portfolio-1',
        title: 'Private Research Draft',
        description: 'Hidden research project',
        source_type: 'manual',
        source_url: null,
        status: 'draft',
        created_at: '2026-04-01T00:00:00.000Z',
        category: 'research',
        tags: ['Research'],
        github_url: null,
        project_url: null,
        image_url: null,
        is_group_project: false,
        personal_contribution: null,
        is_public: false,
    },
];

export const fetchedBasicNarratives = [
    {
        id: 'narrative-1',
        project_id: 'project-1',
        content: 'Built a dashboard with Supabase data.',
        problem: 'Portfolio work is scattered.',
        process: 'Built a dashboard and API service layer.',
        outcome: 'Portfolio content is easier to manage.',
        role: 'Owned the frontend dashboard.',
        is_draft: false,
        version: 1,
        created_at: '2026-01-02T00:00:00.000Z',
        updated_at: '2026-01-02T00:00:00.000Z',
    },
    {
        id: 'narrative-2',
        project_id: 'project-2',
        content: 'Created a design system.',
        problem: 'The project needed a consistent visual direction.',
        process: 'Explored layout, typography, and interface states.',
        outcome: 'Created a cleaner visual system.',
        role: 'Designed the interface direction.',
        is_draft: false,
        version: 1,
        created_at: '2026-03-05T00:00:00.000Z',
        updated_at: '2026-03-05T00:00:00.000Z',
    },
    {
        id: 'narrative-3',
        project_id: 'project-3',
        content: 'This project should not show publicly.',
        problem: '',
        process: '',
        outcome: '',
        role: '',
        is_draft: true,
        version: 1,
        created_at: '2026-04-01T00:00:00.000Z',
        updated_at: '2026-04-01T00:00:00.000Z',
    },
];

export const fetchedBasicShareLink = {
    id: 'share-1',
    portfolio_id: 'portfolio-1',
    share_token: 'share-token-1',
    is_active: true,
    visibility: 'public',
    created_at: '2026-01-01T00:00:00.000Z',
};

export const fetchedBasicVerificationResults = [
    {
        id: 'verification-1',
        project_id: 'project-1',
        status: 'verified',
        score: 0.95,
        feedback: 'Verified from repository evidence.',
        evidence_summary: 'Repository contains React and Supabase work.',
        source_provider: 'github',
        source_url: 'https://github.com/neh5284/alpha',
        created_at: '2026-01-02T00:00:00.000Z',
    },
];

export const testPortfolio: Portfolio = {
    id: 'portfolio-1',
    userId: 'user-1',
    username: 'neh5284',
    displayName: 'Nathan Hinkle',
    title: 'Nathan Portfolio',
    email: 'neh5284@psu.edu',
    tagline: 'Building the future, one project at a time.',
    bio: 'Human-Centered Design and Development student.',
    visibility: 'public',
    shareToken: 'share-token-1',
    shareUrl: '/share/share-token-1',
    projects: [
        {
            id: 'project-1',
            title: 'Alpha Project',
            description: 'React dashboard project',
            narrative: 'Built a dashboard with Supabase data.',
            problem: 'Portfolio work is scattered.',
            process: 'Built a dashboard and API service layer.',
            outcome: 'Portfolio content is easier to manage.',
            role: 'Owned the frontend dashboard.',
            category: 'coding',
            tags: ['React', 'Supabase'],
            projectUrl: 'https://example.com/alpha',
            githubUrl: 'https://github.com/neh5284/alpha',
            createdAt: '2026-01-02T00:00:00.000Z',
            isGroupProject: true,
            personalContribution: 'Owned the frontend dashboard.',
            verified: true,
            isPublic: true,
            verificationStatus: 'verified',
            verificationScore: 0.95,
            verificationFeedback: 'Verified from repository evidence.',
        },
        {
            id: 'project-2',
            title: 'Beta Design',
            description: 'Visual identity project',
            narrative: 'Created a design system.',
            problem: 'The project needed a consistent visual direction.',
            process: 'Explored layout, typography, and interface states.',
            outcome: 'Created a cleaner visual system.',
            role: 'Designed the interface direction.',
            category: 'design',
            tags: ['Figma'],
            createdAt: '2026-03-05T00:00:00.000Z',
            verified: false,
            isPublic: true,
            verificationStatus: 'published',
        },
        {
            id: 'project-3',
            title: 'Private Research Draft',
            description: 'Hidden research project',
            narrative: 'This project should not show publicly.',
            category: 'research',
            tags: ['Research'],
            createdAt: '2026-04-01T00:00:00.000Z',
            verified: false,
            isPublic: false,
            narrativeIsDraft: true,
            verificationStatus: 'draft',
        },
    ],
};